### ISSUE TITLE
link steno with official webpages

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#11]
Currently, the steno shows into the direct source:
https://data.rada.gov.ua/ogd/zal/agenda/skl7/sten/20121204.htm
but it is possible to link it with:
https://www.rada.gov.ua/meeting/stenogr/show/4106.html

the links are reachable from https://data.rada.gov.ua/open/data/stenogram_ses-skl7
where tsv files contains:
```tsv
date	skl	ses	number	class	url	title
20121204	7	1	0	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4106.html	
20121205	7	1	0	b_green		
20121206	7	1	0	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4111.html	
20121212	7	1	0	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4112.html	Óðî÷èñòå çàñ³äàííÿ
20121212	7	1	1	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4113.html	Çàñ³äàííÿ 01 (ðàíêîâå)
20121212	7	1	2	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4115.html	Çàñ³äàííÿ 02 (âå÷³ðíº)
20121213	7	1	0	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4116.html	
20121218	7	1	0	b_yellow	https://www.rada.gov.ua/meeting/stenogr/show/4119.html	
20121219	7	1	0	b_green		
```
The class that contains `_yellow` classifies sitting.

- `skl` = term
- `ses` = parliamentary year (session)
- `number` = the number of sitting in one day

The link to tsv file is reachable from the same file as stenogram_txt zip file.

**Comment by AnnaParla** [comment]
> * `ses` = parliamentary year (session)

For the sake of clarity, regular parliamentary sessions in Ukraine commence twice a year, in February and in September under the Rules of the Verkhovna Rada.

**Comment by matyaskopp** [comment]
`orange` is extraordinary plenary meetings -> this info can be encoded too
