### ISSUE TITLE
taxonomies

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#14]
Translate common ParlaMint taxonomies into Ukrainian

**Comment by matyaskopp** [comment]
I have added common taxonomies to this folder: https://github.com/ufal/ParlaMint-UA/tree/main/Taxonomies
Please translate all taxonomies except [ParlaMint-taxonomy-UD-SYN.ana.xml](https://github.com/ufal/ParlaMint-UA/blob/main/Taxonomies/ParlaMint-taxonomy-UD-SYN.ana.xml) into Ukrainian.

Content for translation is in xml comments:
https://github.com/ufal/ParlaMint-UA/blob/51d053e49f0dd192aea3434f06ab43180b4e597b/Taxonomies/ParlaMint-taxonomy-subcorpus.xml#L12-L13
should be something like:
```XML
      <catDesc xml:lang="uk">
         <term>Посилання</term>: довідковий підкорпус, до 2019-10-31</catDesc>
```

**Comment by AnnaParla** [comment]
Ok, will do.

ср, 11 січ. 2023 р. о 16:37 Matyáš Kopp ***@***.***> пише:
