### ISSUE TITLE
Missing chairman name

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#24]
This sitting does not mention the chairman's name: 
https://www.rada.gov.ua/meeting/stenogr/show/5173.html

- [x] find the name @AnnaParla 
- [ ] figure out how to fix this (when it should be patched) @matyaskopp

**Comment by AnnaParla** [comment]
The Chairman in the sitting is ОлександрВалентиновичТурчинов.1964:
https://docs.google.com/spreadsheets/d/1U6_DF1cF7mS0J4C9WQ1W7OIESRdDek_CbNXxhfXaBkQ/edit?pli=1#gid=983620751&range=B28

1) At 16:32:56 in the transcript, the speaker directly names him by the forename and patronymic and than by the forename and surname. 
2) This sitting was continued from the day before. The transcript for that day directly names two chairmen altering the presiding role. The latter chairman mentioned there is ОлександрВалентиновичТурчинов.1964 (after 13:22:46): https://www.rada.gov.ua/meeting/stenogr/show/5169.html

**Comment by matyaskopp** [comment]
will be fixed in #37
