### ISSUE TITLE
UD invalid syntactic relation xcomp:sp

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#25]
I am running the newest model for udpipe [ukrainian-iu-ud-2.10-220711](https://ufal.mff.cuni.cz/udpipe/2/models#ukrainian-iu-ud-2.10-220711) but it is based on UD v2.10 that contains invalid relation in UA treebank:
http://hdl.handle.net/11346/PMLTQ-CPGD
![image](https://user-images.githubusercontent.com/5867995/217073813-c7515eb8-17f9-4259-a5f9-1e7bf5e437f4.png)

all(100) occurrences of `xcomp:sp` is in v2.11 replaced with `xcomp:pred`:
http://hdl.handle.net/11346/PMLTQ-ZDGV

sample tree: http://hdl.handle.net/11346/PMLTQ-FC47
![image](https://user-images.githubusercontent.com/5867995/217074472-bf191699-c3e5-4f89-a6b5-3430fbf78fc3.png)

@AnnaParla, I am suggesting replacing all(23299) occurrences of `xcomp:sp` with `xcomp:pred`(currently 0 occurrences) if you agree.

**Comment by matyaskopp** [comment]
https://github.com/UniversalDependencies/UD_Ukrainian-IU/blob/38a54d621794527627f6d37f755cdcf5c19a4bfd/README.md?plain=1#L113

**Comment by AnnaParla** [comment]
Yes, xcomp:pred is a "default" solution. All enhanced dependencies would need manual annotation, which we are not doing here.
