### ISSUE TITLE
List of incorrect HTML to TEI conversion

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#29]
Converted data: [02t-tei-text](https://github.com/ufal/ParlaMint-UA/tree/data/02t-tei-text)

### (1) recognizing single name speaker fails

 - [x] is done

related to #28 

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2018/ParlaMint-UA_2018-11-23-m1.xml#L115

**Comment by matyaskopp** [comment]
### (2) huge amount of only-name segments
```
grep -P '>[\p{Lu}\p{Lt}]+[\p{Lu}\p{Lt}\p{Ll}]* [\p{Lu}\p{Lt}]+[\p{Lu}\p{Lt}\p{Ll}]*\.?</seg>'
``` 

the top most:
```
     31 >Олег Ляшко.</seg>
     21 >Руслан Олексійович.</seg>
     17 >Денис Анатолійович.</seg>
     14 >Олександр Сергійович.</seg>
     13 >Олексій Гончаренко.</seg>
     12 >Єгор Соболєв.</seg>
     10 >Слава Україні.</seg>
     10 >Микола Томенко.</seg>
      9 >Ірина Геращенко.</seg>
      8 >Юрій Луценко.</seg>
      8 >Юрій Левченко.</seg>
      8 >Вікторія Сюмар.</seg>
      8 >Андрій Іллєнко.</seg>
      7 >Руслан Князевич.</seg>
      7 >Олег Березюк.</seg>
      7 >Михайло Головко.</seg>
      6 >Сергій Каплін.</seg>
      6 >Сергій Власенко.</seg>
      6 >Павло Кишкар.</seg>
      6 >Нестор Іванович.</seg>
      6 >Мустафа Джемілєв.</seg>
      6 >Михайло Папієв.</seg>
      6 >Ігор Шурма.</seg>
      5 >Сергій Соболєв.</seg>
      5 >Олександре Сергійовичу.</seg>
      5 >Наталія Королевська.</seg>
      5 >Микола Тарасович.</seg>
      5 >Іван Крулько.</seg>
      5 >Віктор Кривенко.</seg>
      5 >Вадим Івченко.</seg>
      4 >Юлія Володимирівна.</seg>
      4 >Сергій Мельничук.</seg>
      4 >Олександр Долженков.</seg>
      4 >Олександра Кужель.</seg>
      4 >Олег Мусій.</seg>
      4 >Ніна Петрівна.</seg>
      4 >Михайло Володимирович.</seg>
      4 >Микола Княжицький.</seg>
```
there are in total 533 occurrences of different "names"

**Comment by matyaskopp** [comment]
### (3) chairman speech is not identified

typo in transcriptions:
- ГОЛ**ОВ**УЮЧИЙ
- ГОЛ**ВО**УЮЧИЙ

https://www.rada.gov.ua/meeting/stenogr/show/6766.html
https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2018/ParlaMint-UA_2018-04-03-m0.xml#L128

https://www.rada.gov.ua/meeting/stenogr/show/6962.html
https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2018/ParlaMint-UA_2018-11-23-m0.xml#L861

**Comment by matyaskopp** [comment]
### (4) interruption by chair

https://www.rada.gov.ua/meeting/stenogr/show/6697.html

![image](https://user-images.githubusercontent.com/5867995/217748508-90a70ae1-7753-4eee-86d2-dfbbae85ba55.png)

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2018/ParlaMint-UA_2018-01-17-m0.xml#L1530-L1540

**Comment by matyaskopp** [comment]
### (5) not identified interruptions (voices in the hall)

https://www.rada.gov.ua/meeting/stenogr/show/5726.html
![image](https://user-images.githubusercontent.com/5867995/217749728-166b89c6-37d6-41c0-bb20-799c7d26aec4.png)

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2014/ParlaMint-UA_2014-12-04-m0.xml#L786

**Comment by matyaskopp** [comment]
### (6) speech not identified when dot is present after surname

https://www.rada.gov.ua/meeting/stenogr/show/5224.html
![image](https://user-images.githubusercontent.com/5867995/217750411-896196f4-30af-46d9-aa9c-b5f1102f6477.png)

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2014/ParlaMint-UA_2014-04-01-m0.xml#L813

**Comment by matyaskopp** [comment]
### (7) unexpected character in name `

https://www.rada.gov.ua/meeting/stenogr/show/4951.html
![image](https://user-images.githubusercontent.com/5867995/217751784-3bbbcdfd-fdb0-44b9-8aaf-5b7116ae2533.png)

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2013/ParlaMint-UA_2013-04-04-m0.xml#L389

**Comment by matyaskopp** [comment]
### (8) invisible content inside the name in source html

https://www.rada.gov.ua/meeting/stenogr/show/6094.html
```HTML
<p class="MsoNormal">ГАЛАСЮ<a name="Temp"></a>К В.В.</p>
```

https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2016/ParlaMint-UA_2016-01-26-m1.xml#L507

**Comment by matyaskopp** [comment]
### (9) religious speaker

https://www.rada.gov.ua/meeting/stenogr/show/6454.html
![image](https://user-images.githubusercontent.com/5867995/217934718-e3e87868-ac31-48ca-aced-d9a4393c3035.png)

https://github.com/ufal/ParlaMint-UA/blob/f6be979f4d97b7d76e30578e2771127249378cf5/02t-tei-text/2017/ParlaMint-UA_2017-03-17-m1.xml#L166

single name was not fixed ???
https://github.com/ufal/ParlaMint-UA/blob/f6be979f4d97b7d76e30578e2771127249378cf5/02t-tei-text/2017/ParlaMint-UA_2017-03-17-m1.xml#L206

**Comment by matyaskopp** [comment]
### (4b) interruption
https://www.rada.gov.ua/meeting/stenogr/show/6908.html

name inside `a` element 
```HTML
<p class="MsoNormal"><a name="Temp">БІЛЕЦЬКИЙ А.Є.</a></p>
```

https://github.com/ufal/ParlaMint-UA/blob/f6be979f4d97b7d76e30578e2771127249378cf5/02t-tei-text/2018/ParlaMint-UA_2018-10-02-m0.xml#L676

**Comment by AnnaParla** [comment]
> Converted data: [02t-tei-text](https://github.com/ufal/ParlaMint-UA/tree/data/02t-tei-text)
> 
> ### (1) recognizing single name speaker fails
> * [x]  is done
> 
> related to #28
> 
> https://github.com/ufal/ParlaMint-UA/blob/8e0d602a969140c426497b2088e68b31bf3d42af/02t-tei-text/2018/ParlaMint-UA_2018-11-23-m1.xml#L115

As for one name religious speakers like ФІЛАРЕТ, I added some of them manually to the quest list a few days ago.

**Comment by matyaskopp** [comment]
### (10) remove invalid content from data

- [ ] is done

https://www.rada.gov.ua/meeting/stenogr/show/5092.html

```HTML
<p class="MsoNormal"><b style="mso-bidi-font-weight:normal"><span style="color:green" lang="UK">Фрг__03859*003*031&lt;13:43:51&gt;&lt;ДанильченкоМ.В.&gt;</span></b><b style="mso-bidi-font-weight:normal"><span style="color:red" lang="UK"></span></b></p>
```
![image](https://user-images.githubusercontent.com/5867995/218074341-b640a60a-a1a7-4d27-aeb1-2e5b4c78ecba.png)
