### ISSUE TITLE
Affiliation roles taxonomy

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#31]
add uk translations:
https://github.com/ufal/ParlaMint-UA/blob/ef97e23401ce1069224ab3a4ed12e2347813f0b1/Taxonomies/ParlaMint-UA-taxonomy-affiliation.roles.xml#L1-L11

**Comment by AnnaParla** [comment]
For some reason, the system doesn't let me edit inside [ParlaMint-UA/Taxonomies/ParlaMint-UA-taxonomy-affiliation.roles.xml](https://github.com/ufal/ParlaMint-UA/blob/ef97e23401ce1069224ab3a4ed12e2347813f0b1/Taxonomies/ParlaMint-UA-taxonomy-affiliation.roles.xml#L1-L11)

> <catDesc xml:lang="uk"><term></term>: </catDesc>
<catDesc xml:lang="uk">Виконувач обов'язків</term>: </catDesc>

**Comment by AnnaParla** [comment]
Cool!
Done but there is a punctuation question. I cannot think of an elegant way of translating "Extended affiliation roles" into Ukrainian as a single phrase. So I would like to break in into "приналежність: розширені ролі". The question is whether I can use a semicolon between the angle brackets or I need to come up with a different punctuation mark for any technical reasons.

**Comment by matyaskopp** [comment]
It is ok, or you can extend the description. Or you can use a shorter term and add a description:
```XML
    <desc xml:lang="uk"><term>розширені ролі</term>: DESCRIPTION</desc> 
```

Can you also add a description of the acting role - what it does mean (both in en and UK versions):
```XML
    <category xml:id="affiliation.role.acting"> 
       <catDesc xml:lang="uk"><term>Виконувач обов'язків</term>: DESCRIPTION</catDesc> 
       <catDesc xml:lang="en"><term>Acting</term>: DESCRIPTION</catDesc> 
    </category> 
```

Everybody who will possibly use our taxonomy should understand it...
