### ISSUE TITLE
Check and translate corpus and component file header

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#34]
You can set a sample in this issue as the comment, and I will then transfer it into code.
Not everything should be translated - the most important is `fileDesc` element. 

Corpus file:  https://github.com/matyaskopp/ParlaMint/blob/8b1ac4c8ae90e44242d1da0356fc850b5c684a7a/Data/ParlaMint-UA/ParlaMint-UA.ana.xml#L6-L60
Component file: https://github.com/matyaskopp/ParlaMint/blob/8b1ac4c8ae90e44242d1da0356fc850b5c684a7a/Data/ParlaMint-UA/ParlaMint-UA.ana.xml#L6-L60

- [x] @AnnaParla: translation
- [x] @AnnaParla: check the whole headers
- [x] @matyaskopp: implement changes in code
- [x] @matyaskopp: regenerate sample
- [x] @AnnaParla: check header again

**Comment by AnnaParla** [comment]
<fileDesc>
         <titleStmt>
            <title type="main" xml:lang="en">Ukrainian parliamentary corpus ParlaMint-UA [ParlaMint.ana]</title>
            <title type="sub" xml:lang="uk">Корпус Верховної Ради України ParlaMint-UA [ParlaMint.ana]</title>
            <title type="sub" xml:lang="en">Ukrainian parliament 2012-12-12 - 2022-12-01</title>
           <title type="sub" xml:lang="uk">Корпус стенограм Верховної Ради України за період з 2012-12-12 по 2022-12-01</title>
            <meeting ana="#parla.term #parla.uni" n="7">7</meeting>
            <meeting ana="#parla.term #parla.uni" n="8">8</meeting>
            <meeting ana="#parla.term #parla.uni" n="9">9</meeting>
            <respStmt>
               <persName ref="https://orcid.org/0000-0001-7953-8783">Matyáš Kopp</persName>
               <resp xml:lang="en">Data retrieval</resp>
               <resp xml:lang="uk">Збирання даних</resp>
               <resp xml:lang="en">TEI XML corpus encoding</resp>
               <resp xml:lang="uk">Програмування корпусу у форматі TEI XML</resp>
               <resp xml:lang="en">Linguistic annotation</resp>
               <resp xml:lang="uk">Мовна розмітка</resp>
            </respStmt>
            <respStmt>
               <persName>Anna Kryvenko</persName>
               <resp xml:lang="en">Manual metadata retrieval</resp>
               <resp xml:lang="uk">Ручне збирання метаданих</resp>
               <resp xml:lang="en">Translations</resp>
               <resp xml:lang="uk">Переклад</resp>
            </respStmt>
            <funder>
               <orgName xml:lang="en">CLARIN ERIC</orgName>
            </funder>
            <funder>
               <orgName xml:lang="en">Slovenian Research Agency</orgName>
               <orgName xml:lang="uk">Державне дослідницьке агентство Республіки Словенія</orgName>
            </funder>
         </titleStmt>
         <editionStmt>
            <edition>3.0a</edition>
         </editionStmt>
         <extent>
            <measure unit="speeches" quantity="1051" xml:lang="en">1051 speeches</measure>
            <measure unit="speeches" quantity="1051" xml:lang="uk">1051 виступів</measure>
            <measure unit="words" quantity="116466" xml:lang="en">116466 words</measure>
            <measure unit="words" quantity="116466" xml:lang="uk">116466 слів</measure>
         </extent>
         <publicationStmt>
            <publisher>
               <orgName xml:lang="en">CLARIN research infrastructure</orgName>
               <orgName xml:lang="uk">Дослідницька інфраструктура CLARIN</orgName>
               <ref target="https://www.clarin.eu/">www.clarin.eu</ref>
            </publisher>
            <idno type="URI" subtype="handle">http://hdl.handle.net/11356/XXXX</idno>
            <availability status="free">
               <licence>http://creativecommons.org/licenses/by/4.0/</licence>
               <p xml:lang="en">This work is licensed under the <ref target="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</ref>.</p>
               <p xml:lang="uk">Цей твір ліцензовано на умовах <ref target="http://creativecommons.org/licenses/by/4.0/">"Міжнародної ліцензії Creative Commons 4.0 із зазначенням авторства"</ref>.</p>
            </availability>
            <date when="2023-02-13">2023-02-13</date>
         </publicationStmt>
         <sourceDesc>
            <bibl>
               <title type="main" xml:lang="uk">Верхо́вна Ра́да Украї́ни</title>
               <idno type="URI" subtype="parliament">https://www.rada.gov.ua/meeting/stenogr/</idno>
               <date from="2012-12-12" to="2022-12-01">2012-12-12 - 2022-12-01</date>
            </bibl>
         </sourceDesc>
      </fileDesc>

**Comment by AnnaParla** [comment]
> You can set a sample in this issue as the comment, and I will then transfer it into code.

It did not quite work out. All the line numbers are gone. Is it a problem for you and can I fix it?

**Comment by AnnaParla** [comment]
Are the corpus file and the component file identical, as far as the translated part is concerned?

**Comment by AnnaParla** [comment]
Btw, do you want to keep word accents on "Верхо́вна Ра́да Украї́ни" in the yellow section and below where the setting is described? We do not use them in writing unless it is done for special purposes in a textbook or a dictionary.

**Comment by matyaskopp** [comment]
> Are the corpus file and the component file identical, as far as the translated part is concerned?

Component files have minor differences. Current state - with your translations:
```XML
      <fileDesc>
         <titleStmt><!--TODO: title-->
            <title type="main" xml:lang="en">Ukrainian parliamentary corpus ParlaMint-UA, term 9, session 8, sitting day 2022-12-01 n0 [ParlaMint.ana]</title>
            <meeting ana="#parla.term #parla.uni" n="9">9</meeting>
            <meeting ana="#parla.session #parla.uni" n="8">8</meeting>
            <meeting ana="#parla.sitting #parla.uni" n="2022-12-01">2022-12-01</meeting>
            <respStmt>
               <persName ref="https://orcid.org/0000-0001-7953-8783">Matyáš Kopp</persName>
               <resp xml:lang="en">Data retrieval</resp>
               <resp xml:lang="uk">Збирання даних</resp>
               <resp xml:lang="en">TEI XML corpus encoding</resp>
               <resp xml:lang="uk">Програмування корпусу у форматі TEI XML</resp>
               <resp xml:lang="en">Linguistic annotation</resp>
               <resp xml:lang="uk">Мовна розмітка</resp>
            </respStmt>
            <respStmt>
               <persName>Anna Kryvenko</persName>
               <resp xml:lang="en">Manual metadata retrieval</resp>
               <resp xml:lang="uk">Ручне збирання метаданих</resp>
               <resp xml:lang="en">Translations</resp>
               <resp xml:lang="uk">Переклад</resp>
            </respStmt>
            <funder>
               <orgName xml:lang="en">CLARIN ERIC</orgName>
            </funder>
            <funder>
               <orgName xml:lang="en">Slovenian Research Agency</orgName>
               <orgName xml:lang="uk">Державне дослідницьке агентство Республіки Словенія</orgName>
            </funder>
         </titleStmt>
         <editionStmt>
            <edition>3.0a</edition>
         </editionStmt>
         <extent>
            <measure unit="speeches" quantity="186" xml:lang="en">186 speeches</measure>
            <measure unit="speeches" quantity="186" xml:lang="uk">186 виступів</measure>
            <measure unit="words" quantity="20307" xml:lang="en">20307 words</measure>
            <measure unit="words" quantity="20307" xml:lang="uk">20307 слів</measure>
         </extent>
         <publicationStmt>
            <publisher>
               <orgName xml:lang="en">CLARIN research infrastructure</orgName>
               <orgName xml:lang="uk">Дослідницька інфраструктура CLARIN</orgName>
               <ref target="https://www.clarin.eu/">www.clarin.eu</ref>
            </publisher>
            <idno type="URI" subtype="handle">http://hdl.handle.net/11356/XXXX</idno>
            <availability status="free">
               <licence>http://creativecommons.org/licenses/by/4.0/</licence>
               <p xml:lang="en">This work is licensed under the <ref target="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</ref>.</p>
               <p xml:lang="uk">Цей твір ліцензовано на умовах <ref target="http://creativecommons.org/licenses/by/4.0/">"Міжнародної ліцензії Creative Commons 4.0 із зазначенням авторства"</ref>.</p>
            </availability>
            <date when="2023-02-21">2023-02-21</date>
         </publicationStmt>
         <sourceDesc>
            <bibl>
               <title type="main" xml:lang="uk">Верхо́вна Ра́да Украї́ни</title>
               <idno type="URI" subtype="parliament">https://www.rada.gov.ua/meeting/stenogr/show/8084.html</idno>
               <date when="2022-12-01">2022-12-01</date>
            </bibl>
         </sourceDesc>
      </fileDesc>
      <encodingDesc>
         <projectDesc>
            <p xml:lang="uk">
               <ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>
            </p>
            <p xml:lang="en">
               <ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>, covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and machine-translate them to English; (3) make the corpora available through concordancers; and (4) build use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
         </projectDesc>
```
So it seems that only `<title>` and `<projectDesc>` need to be translated

> Btw, do you want to keep word accents on "Верхо́вна Ра́да Украї́ни" in the yellow section and below where the setting is described? We do not use them in writing unless it is done for special purposes in a textbook or a dictionary.

No, it os a copy-paste result. You can remove it.

**Comment by AnnaParla** [comment]
ok
The missing translation in the component file is below, incl. the <sourceDesc> section with the "Верховна Рада України" without word accents. Also, I changed the order of the uk and en descriptions in the <projectDesc>, so that it would match the language order in the rest of the doc.  

Questions: 

Do you need a coma between the date and the setting number in <title type="main" xml:lang="en">?
I mean "2022-12-01, n0". In Ukrainian you do, if I understand this expression correctly. 

If there is a morning meeting and an evening meeting on the same sitting day, will you keep them separated or merge them into one unit under that date?   

Btw, the term number is traditionally written in Latin ordinal numbers and the session number is written in Ukrainian words. Is it a problem for this document? Shall I stick only to Arabic numbers instead? If yes, I will edit this translation asap. 
 
...........................................
<fileDesc>
         <titleStmt>
            <title type="main" xml:lang="en">Ukrainian parliamentary corpus ParlaMint-UA, term 9, session 8, sitting day 2022-12-01 n0 [ParlaMint.ana]</title>
            <title type="main" xml:lang="uk">Корпус Верховної Ради України ParlaMint-UA, ІХ скликання, восьма сесія, дата пленарного засідання 2022-12-01, номер засідання №0 [ParlaMint.ana]</title>

...................
        <sourceDesc>
            <bibl>
               <title type="main" xml:lang="uk">Верховна Рада України</title>
               <idno type="URI" subtype="parliament">https://www.rada.gov.ua/meeting/stenogr/show/8084.html</idno>
               <date when="2022-12-01">2022-12-01</date>
            </bibl>
         </sourceDesc>
</fileDesc>
<encodingDesc>
         <projectDesc>
            <p xml:lang="en">
               <ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>, covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and machine-translate them to English; (3) make the corpora available through concordancers; and (4) build use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
           <p xml:lang="uk">
               <ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> — проєкт, цілями якого є: (1) створення багатомовної групи порівнянних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>
         </projectDesc>

**Comment by AnnaParla** [comment]
<@AnnaParla: check the whole headers>

What do these headers look like in this documentation and where do I find them? "Header" is a polysemous word, so I want to make sure that I recognize the right entities denominated by this term. :)

**Comment by matyaskopp** [comment]
I have updated `<teiHeader>` content + replaced all numbers with arabic (it is automatically generated, so it is easier for me).

header = content of `<teiHeader>` element. You should only check a root file: https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml
and one component file:
https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/2012/ParlaMint-UA_2012-12-12-m0.xml

**Comment by AnnaParla** [comment]
Done. Spotted a couple of typos and offered changes inside the files. Hopefully, you can see them.

**Comment by matyaskopp** [comment]
@AnnaParla 

I cant see your commits. Have you pushed them to GitHub?

**Comment by AnnaParla** [comment]
> @AnnaParla
> 
> I cant see your commits. Have you pushed them to GitHub?

I came across a function "suggest corrections/change", corrected the typos and suggested change this way. 
Copying the lines needing corrections below:


From  https://github.com/matyaskopp/ParlaMint/edit/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml

Old (wrong):
 <title type="main" xml:lang="uk">&gt;Корпус Верховної Ради України ParlaMint-UA [ParlaMint.ana]</title>

New (right):
 <title type="main" xml:lang="uk">Корпус Верховної Ради України ParlaMint-UA [ParlaMint.ana]</title>


From https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/2012/ParlaMint-UA_2012-12-12-m0.xml

Old (wrong):
<ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>  — проєкт, цілями якого є: (1) створення багатомовної групи порівнянних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>
            
New (right):
<ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>  — проєкт, цілями якого є: (1) створення багатомовної групи порівняльних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>

**Comment by matyaskopp** [comment]
> Old (wrong): `<title type="main" xml:lang="uk">Корпус Верховної Ради України ParlaMint-UA [ParlaMint.ana]</title>`
> 
> New (right): `<title type="main" xml:lang="uk">Корпус Верховної Ради України ParlaMint-UA [ParlaMint.ana]</title>`

@AnnaParla, I dont see the difference here

**Comment by AnnaParla** [comment]
It is a bit strange... If you follow the link (https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml), that version has 4 extra characters in blue on line 9 after the angle bracket "uk">&gt;Корпус
  
Maybe you can see it on the screenshot below, or I will send it by email. 
![image](https://user-images.githubusercontent.com/115141649/221848970-c243c562-e1f3-4a85-94b5-a67eacd9b211.png)

**Comment by matyaskopp** [comment]
@AnnaParla 
everything is fixed. Can you recheck the header please?

**Comment by AnnaParla** [comment]
It all looks good to me. However, may I ask you to please replace line 11 in (https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml). The new version is more transparent and comprehensible. Other than that it is good to go.   
Old: 
<title type="sub" xml:lang="uk">Корпус стенограм Верховної Ради України за період з 2012-12-12 по 2022-12-01</title>

New: 
<title type="sub" xml:lang="uk">Стенограми пленарних засідань Верховної Ради України за період з 2012-12-12 по 2022-12-01</title>

**Comment by matyaskopp** [comment]
Everything is implemented, closing.

**Comment by AnnaParla** [comment]
Please insert lines 10 and 11 with the updated dates:
<title type="sub" xml:lang="en">Ukrainian parliament 2012-12-12 - 2023-02-24</title>
<title type="sub" xml:lang="uk">Стенограми пленарних засідань Верховної Ради України за період з 2012-12-12 по 2023-02-24</title>

in https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml

**Comment by matyaskopp** [comment]
> @matyaskopp Please insert lines 10 and 11 with the updated dates:
> 
> <title type="sub" xml:lang="en">Ukrainian parliament 2012-12-12 - 2023-02-24</title> <title type="sub" xml:lang="uk">Стенограми пленарних засідань Верховної Ради України за період з 2012-12-12 по 2023-02-24</title>
> in https://github.com/matyaskopp/ParlaMint/blob/data-UA/Data/ParlaMint-UA/ParlaMint-UA.ana.xml

the correct dates are inserted automatically

**Comment by AnnaParla** [comment]
Good to know :)
