### ISSUE TITLE
space in PUNCT

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#40]
Due to crazy tokenization, there is one occurrence of `<pc>` element with space.

Sentence
> Я би вас попросила все-таки прокоментувати 30 поправку, яка стосується того, що рекомендації щодо захисту інших мов (це CDL-АD 044 і Розділ С) і Захист індивідуальної свободикористування мовою за вибором (Розділ D).

is tokenized this way: (problematic is token **-АD 044** )
![image](https://user-images.githubusercontent.com/5867995/222541135-87b06b28-84eb-4398-a773-74331cedefd7.png)

a possible solution is whenever **form contains space**  and **UPosTag=PUNCT** then replace values in line with:
- UPosTag=**X**
- Feats=**_**
-  Deprel=**dep** (if not root)

if UPosTag is not PUNCT then element `<w>` is used and space is allowed there

**Comment by matyaskopp** [comment]
@AnnaParla, do you have a better idea?

**Comment by AnnaParla** [comment]
Unfortunately, the original data do not always differentiate between dash (<pc>) and hyphen (within <w>). 

Shouldn't stems with a hyphen in between and no space before and after or just no space before (in case a complex word or just a long word is broken into two lines) be recognized as 1 token (CDL-АD)?

In case of dash, there is a space before and a space after.

**Comment by matyaskopp** [comment]
Yes, I know that tokenization is wrong here. I just wanted to find some lazy solution. 
I have an idea for fixing tokenization and wrong sentence segmentation, but it is a lot of work, and I am not sure if new bugs will be introduced.
So I want a simple solution. There will be a new udpipe at the end of 2023, so I hope the tokenization issues will be fixed there - so I am suggesting leaving it to the next release.

**Comment by AnnaParla** [comment]
Ok, let's leave it for now.

**Comment by matyaskopp** [comment]
I have decided for simpler solution - just replace `<pc>` with `<w>` when space is present in form
