### ISSUE TITLE
Can the "from" date of ВолодимирБорисовичГройсман.1978 party affiliation be changed? 

### ISSUE THREAD

**Issue by AnnaParla** [ufal/ParlaMint-UA#58]
I spotted this error and fixed it in the google sheet
![image](https://github.com/ufal/ParlaMint-UA/assets/115141649/da43ab02-a4b5-458e-b553-e92bd0743878)

**Comment by matyaskopp** [comment]
If it is an error in Google Sheets, then it can be fixed in Google Sheets.

But if this error sources from the Rada database, I am not able to overwrite it with data from Google Sheets (I can add this affiliation aside to affiliation from the Rada source and they are merged in finalization)

**Comment by AnnaParla** [comment]
It is my error in Google Sheets, which I have finally spotted and fixed in Google Sheets.
