### ISSUE TITLE
Please add a transcript from 2019

### ISSUE THREAD

**Issue by AnnaParla** [ufal/ParlaMint-UA#59]
I could find it only as a pdf file. The transcript is on pp. 3-52. I will manually add the missing speakers to the google sheet. 

https://www.rada.gov.ua/uploads/documents/55482.pdf

**Comment by matyaskopp** [comment]
@AnnaParla I will first build the whole corpus and validate it - to have something, and then, if I have time, I will convert this transcript - it requires some investigation on how to do it...

**Comment by AnnaParla** [comment]
Here is [19-02-2019_ВР_ТУСК!!!_ed.txt](https://gist.github.com/AnnaParla/1e53f80201c4f6b135bb23eb461d3502) for your convenience, once you have time for it.
