### ISSUE TITLE
add missing translations in taxonomies

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#62]
taxonomies are stored here: https://github.com/ufal/ParlaMint-UA/tree/main/Taxonomies
eg this file:
https://github.com/ufal/ParlaMint-UA/blob/728d689a2573cbe99a36564d3abce32ff338a3bd/Taxonomies/ParlaMint-taxonomy-subcorpus.xml#L29-L30

**Comment by matyaskopp** [comment]
@AnnaParla, this is the only thing left to have the sample valid.
List of errors (missing translations): https://github.com/clarin-eric/ParlaMint/actions/runs/6117932924

**Comment by matyaskopp** [comment]
@AnnaParla can you please translate other taxonomies? I can see only this change: https://github.com/ufal/ParlaMint-UA/commit/a4dcd6d34b23bf1c13bc1610313f1c5c87c91cc8

The following needs translations too:
- https://github.com/ufal/ParlaMint-UA/blob/main/Taxonomies/ParlaMint-taxonomy-politicalOrientation.xml
https://github.com/ufal/ParlaMint-UA/blob/a4dcd6d34b23bf1c13bc1610313f1c5c87c91cc8/Taxonomies/ParlaMint-taxonomy-politicalOrientation.xml#L122-L154

- https://github.com/ufal/ParlaMint-UA/blob/main/Taxonomies/ParlaMint-taxonomy-subcorpus.xml
https://github.com/ufal/ParlaMint-UA/blob/a4dcd6d34b23bf1c13bc1610313f1c5c87c91cc8/Taxonomies/ParlaMint-taxonomy-subcorpus.xml#L24-L32

**Comment by AnnaParla** [comment]
Hi!

Translating them now.

Best,
Anna

пт, 8 вер. 2023 р. о 18:07 Matyáš Kopp ***@***.***> пише:

**Comment by AnnaParla** [comment]
Done! Some terms were not immediately available in uk Wikipedia or dictionaries so it took me some time to check their conventional wording in the literature on political science.
