### ISSUE TITLE
Add metadata on parliamentary group membership for Term 4, if possible

### ISSUE THREAD

**Issue by AnnaParla** [ufal/ParlaMint-UA#63]
Hi! 
This is to let you know that we have completed linking persons and faction / group membership for Term 4 on the respective page in the google sheet "Speaker and party metadata" and I also added new orgIDs to the org page. Now we have data on faction / group membership with accurate (hopefully) from and to dates for Terms 4-9! 

- [ ] Can this added data be used in the ParlaMint v 4.0? Or,
- [x] Shall it be included only in the 2004-2012 extension?

**Comment by matyaskopp** [comment]
We will include it in our extension, data for v4.0 are now stable and are processed now

**Comment by matyaskopp** [comment]
@AnnaParla please check sheet **affiliationExtra** which contain validation of data you inserted in **Faction-group_membership**:
![image](https://github.com/ufal/ParlaMint-UA/assets/5867995/43f8df06-4ffd-47f3-babb-82dbb4f89620)

**Comment by AnnaParla** [comment]
@matyaskopp Done. ERR: org  were caused by extra spaces after the org name (and extra letters in one case).
