### ISSUE TITLE
Finalization script metadata update

### ISSUE THREAD

**Issue by AnnaParla** [ufal/ParlaMint-UA#71]
- [x] funders
- [x] project description
- [x] authors
- [x] set repository handlers for
    - [x] TEI
    - [x] TEI.ana
- [x] modify publisher

**Comment by AnnaParla** [comment]
<funder>
      <orgName xml:lang="en">CLARIN ERIC</orgName>
      <orgName xml:lang="uk">Загальна дослідницька інфраструктура мовних ресурсів і технологій</orgName>
    </funder>
    <funder>
      <orgName xml:lang="en">Slovenian Research and Innovation Agency</orgName>
      <orgName xml:lang="uk">Державне агентство з управління науковими дослідженями та інноваційною діяльністю Республіки Словенія</orgName>
    </funder>
    <funder>
      <orgName xml:lang="en">CLARIN.SI</orgName>
      <orgName xml:lang="uk">Словенська дослідницька інфраструктура мовних ресурсів і технологій</orgName>
    </funder>

**Comment by AnnaParla** [comment]
@matyaskopp As for the project description, will it suffice to just add at the beginning that this is an extension of the ParlaMint project and keep the rest unchanged, or do we need to introduce more distinctions between this and the ParlaMint-UA proper?

**Comment by AnnaParla** [comment]
@matyaskopp Re the authors, let's see if the other group members provide any deliverables in the next few days and make a final decision then.

**Comment by matyaskopp** [comment]
> @matyaskopp As for the project description, will it suffice to just add at the beginning that this is an extension of the ParlaMint project and keep the rest unchanged, or do we need to introduce more distinctions between this corpus and the ParlaMint-UA proper?

@AnnaParla , the best solution is to add another paragraph (in `uk` and in `en`). The first paragraph probably should be the common ParlaMint description and the second codeswitching project description.

**Comment by AnnaParla** [comment]
<xsl:template name="add-projectDesc">
    <projectDesc>
      <p xml:lang="en"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>, covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and machine-translate them to English; (3) make the corpora available through concordancers; and (4) build use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
      <p xml:lang="en">The Ukrainian parliamentary corpus ParlaMint-UA 4.0.1 is an extended version of the ParlaMint-UA corpus covering the period between 2002 and late 2023 and providing language identification at the sentence level to facilitate research on code-switching.</p>     
      <p xml:lang="uk"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>  — проєкт, цілями якого є: (1) створення багатомовної групи порівняльних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>
      <p xml:lang="en">Український парламентський корпус ParlaMint-UA 4.0.1 — це розширена версія корпусу ParlaMint-UA, яка охоплює період між 2002 і кінцем 2023 року та забезпечує ідентифікацію мови на рівні речень для сприяння дослідженям процесів перемикання мовних кодів.</p>
    </projectDesc>
  </xsl:template>

**Comment by AnnaParla** [comment]
How do you make it show the script on the gray background?

**Comment by matyaskopp** [comment]
> How do you make it show the script on the gray background?

select the content you want with gray background (code) and click on `<>` icon, it is then surrounded with ``` and visualized as code

**Comment by AnnaParla** [comment]
> ```
>   <xsl:template name="add-projectDesc">
>     <projectDesc>
>       <p xml:lang="en"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>, covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and machine-translate them to English; (3) make the corpora available through concordancers; and (4) build use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
>       <p xml:lang="en">The Ukrainian parliamentary corpus ParlaMint-UA 4.0.1 is an extended version of the ParlaMint-UA corpus covering the period between 2002 and late 2023 and providing language identification at the sentence level to facilitate research on code-switching.</p>     
>       <p xml:lang="uk"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>  — проєкт, цілями якого є: (1) створення багатомовної групи порівняльних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>
>       <p xml:lang="en">Український парламентський корпус ParlaMint-UA 4.0.1 — це розширена версія корпусу ParlaMint-UA, яка охоплює період між 2002 і кінцем 2023 року та забезпечує ідентифікацію мови на рівні речень для сприяння дослідженям процесів перемикання мовних кодів.</p>
>     </projectDesc>
>   </xsl:template>
> ```

Just spotted a mistake in the line <<p xml:lang="en">Український парламентський корпус ParlaMint-UA 4.0.1 — >, which should be <<p xml:lang="uk">Український парламентський корпус ParlaMint-UA 4.0.1 — >!!!

**Comment by matyaskopp** [comment]
> > ```
> >   <xsl:template name="add-projectDesc">
> >     <projectDesc>
> >       <p xml:lang="en"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref> is a project that aims to (1) create a multilingual set of comparable corpora of parliamentary proceedings uniformly encoded according to the <ref target="https://clarin-eric.github.io/ParlaMint/">ParlaMint encoding guidelines</ref>, covering the period from 2015 to mid-2022; (2) add linguistic annotations to the corpora and machine-translate them to English; (3) make the corpora available through concordancers; and (4) build use cases in Political Sciences and Digital Humanities based on the corpus data.</p>
> >       <p xml:lang="en">The Ukrainian parliamentary corpus ParlaMint-UA 4.0.1 is an extended version of the ParlaMint-UA corpus covering the period between 2002 and late 2023 and providing language identification at the sentence level to facilitate research on code-switching.</p>     
> >       <p xml:lang="uk"><ref target="https://www.clarin.eu/content/parlamint">ParlaMint</ref>  — проєкт, цілями якого є: (1) створення багатомовної групи порівняльних корпусів стенограм парламентських пленарних засідань, які охоплюють період між 2015 роком і серединою 2022 року та які було розроблено відповідно до спільних для всіх інструкцій <ref target="https://clarin-eric.github.io/ParlaMint/">Інструкції щодо програмування ParlaMint</ref>; (2) лінгвістичне анотування корпусів текстів та їх машинний переклад англійською мовою; (3) забезпечення вільного доступу до корпусів через конкордансери; і (4) створення на основі корпусних даних варіантів використання в галузях політичних наук і цифрових гуманітарних наук.</p>
> >       <p xml:lang="en">Український парламентський корпус ParlaMint-UA 4.0.1 — це розширена версія корпусу ParlaMint-UA, яка охоплює період між 2002 і кінцем 2023 року та забезпечує ідентифікацію мови на рівні речень для сприяння дослідженям процесів перемикання мовних кодів.</p>
> >     </projectDesc>
> >   </xsl:template>
> > ```
> 
> `Just spotted a mistake in the line <p xml:lang="en">Український парламентський корпус ParlaMint-UA 4.0.1 — >, which should be <p xml:lang="uk">Український парламентський корпус ParlaMint-UA 4.0.1 — >!!!`

I spotted it as well, already fixed in https://github.com/ufal/ParlaMint-UA/commit/d254b09d416f1e8f3d3240139b950491004468f3
