### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParlaMint-UA#73]
Update readme describing the corpus (in code-switching) branch: https://github.com/ufal/ParlaMint-UA/blob/code-switching/README-ParlaMint.md
- [x] timespan
- [x] language models
- [x] language identification description

**Comment by AnnaParla** [comment]
Questions: 
- is it ok to commit changes directly to the branch, or
- shall I create a new branch for this commit and start a pull request?

**Comment by matyaskopp** [comment]
you can commit it directly in the branch

**Comment by AnnaParla** [comment]
Also, you mentioned improving normalization in this extension. How? And shall I include in in the readme?

**Comment by matyaskopp** [comment]
> * which UDPipe and language models did you use for POS tagging, lemmatization and dependency parsing for 4.0.1: UDPipe 2 (http://ufal.mff.cuni.cz/udpipe/2) with ukrainian-iu-ud-2.10-220711 and russian-syntagrus-ud-2.10-220711 models, OR ukrainian-iu-ud-2.12-230717 and russian-syntagrus-ud-2.12-230717?

I used ukrainian-iu-ud-2.12-230717 and russian-syntagrus-ud-2.12-230717



> * how did you count the number of tokens in language? Based on "expected frequencies for Ukrainian- and Russian-specific characters in the corpus (6.23 %(і) + 0.84 %(ї) + 0.39 %(є) + 0.01 %(ґ) = 7.47 % for Ukrainian, and 2.36 %(ы) + 0.36 %(э) + 0.2% (ё) + 0.02 %(ъ) = 2.94% for Russian), corpus-specific frequency word lists in Ukrainian and Russian, and Perl package Lingua::Identify::Any. A limitation of 250 characters was used for making decisions on language identification of shorter utterances based on Ukrainian-specific words, with a limitation of 100 characters for Russian-specific words.". ?

This was not used at all, the language identification has been done from scratch. 


> Also, you mentioned improving normalization in this extension. How? And shall I include it in the readme?

not necessary to mention, I discovered that sometimes was not ` character replaced with ukrainian one.
Aso bit of notes polishing was done

**Comment by AnnaParla** [comment]
Well, in the original readme, we have "Regular apostrophes were replaced with soft apostrophes, which are used in the Ukrainian language." Shall I mention anything about any additional cleanup when these replacements failed?

**Comment by matyaskopp** [comment]
> Well, in the original readme, we have "Regular apostrophes were replaced with soft apostrophes, which are used in the Ukrainian language." Shall I mention anything about any additional cleanup when these replacements failed?

it is not important,  do not mention it

**Comment by AnnaParla** [comment]
Done but if you have a moment, it would be great if you could scan it for any errors or mistakes.
